{% set name = "boto3-stubs-lite" %}
{% set version = "1.28.16" %}
{% set lib_version = version.split(".post")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c027c01e5a897adfdcd78b7ed3f5a539eed1d1793304fe1cd10f85009fe58c7

build:
  number: 0
  noarch: python
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    # Note: botocore is also an implicit dependency via mypy_boto3_* → boto3 → botocore,
    # so the following line is redundant.
    - botocore
    - types-s3transfer

outputs:
  - name: boto3-stubs-lite
    build:
      noarch: python
      script:
        - python -m pip install . -vv
    requirements:
      run:
        - boto3
        - typing_extensions
    test:
      commands:
        - pip check
        - python -c 'import importlib; importlib.import_module("boto3-stubs")'
      requires:
        - pip


  - name: boto3-stubs-lite-essential
    build:
      noarch: python
    requirements:
      run:
        # <https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions>
        # <https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-at-the-recipe-level>
        - {{ pin_subpackage(name, exact=True) }}
        # For the dependencies, use the pin >=MAJOR.MINOR
        - {{ pin_compatible('mypy_boto3_cloudformation', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_dynamodb', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_ec2', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_lambda', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_rds', min_pin='x.x') }}
        - {{ pin_compatible('mypy-boto3-s3', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_sqs', min_pin='x.x') }}
    test:
      imports:
        - mypy_boto3_cloudformation
        - mypy_boto3_dynamodb
        - mypy_boto3_ec2
        - mypy_boto3_lambda
        - mypy_boto3_rds
        - mypy_boto3_s3
        - mypy_boto3_sqs
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for boto3 {{ lib_version }}, generated with mypy-boto3-builder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/vemel/mypy_boto3_builder
  doc_url: https://youtype.github.io/boto3_stubs_docs/

extra:
  recipe-maintainers:
    - vemel
    - maresb
